Repository splewis/get5, pull requests merged in 2022-10, with the labels that each got.

#888 Fix problems with knife swap/stay command timing
  cfg/get5/knife.cfg
  documentation/docs/configuration.md
  scripting/get5.sp
  scripting/get5/kniferounds.sp
  scripting/get5/matchconfig.sp
Labels: bug

#890 Remove team ready tags if there is no knife round
  scripting/get5/goinglive.sp
Labels: bug

#891 Disallow suicide via console
  scripting/get5.sp
Labels: bug, enhancement

#886 Add command to request surrender win instead of automatic trigger
  documentation/docs/commands.md
  documentation/docs/configuration.md
  documentation/docs/translations.md
  scripting/get5.sp
  scripting/get5/backups.sp
  scripting/get5/matchconfig.sp
  scripting/get5/pausing.sp
  scripting/get5/surrender.sp
  scripting/get5/util.sp
  scripting/include/get5.inc
  translations/da/get5.phrases.txt
  translations/get5.phrases.txt
  translations/pt/get5.phrases.txt
  translations/ru/get5.phrases.txt
Labels: bug, enhancement, translation

#895 Add more event data
  documentation/docs/event_schema.yml
  scripting/get5.sp
  scripting/get5/recording.sp
  scripting/include/get5.inc
Labels: enhancement

#896 Cleaned up remote match load logic
  documentation/docs/commands.md
  scripting/get5.sp
  scripting/get5/matchconfig.sp
Labels: Optimization/Cleanup

#894 Avoid restarting demo recording if restoring to the same match/map
  scripting/get5.sp
  scripting/get5/backups.sp
Labels: enhancement

#899 Update deps for workflows to avoid deprecation.
  .github/workflows/build.yml
  .github/workflows/development.yml
  .github/workflows/generate_docs.yml
Labels: Optimization/Cleanup

#906 Add delay for team placement when joining the server
  scripting/get5/teamlogic.sp
Labels: bug

#904 Update German translation
  translations/de/get5.phrases.txt
Labels: translation

#916 Fix inability to join a team if get5 is not running
  scripting/get5/teamlogic.sp
Labels: bug

#909 Fix "CTs win" callout before knife round + Prevent connecting users from joining teams too early
  scripting/get5.sp
  scripting/get5/kniferounds.sp
  scripting/get5/matchconfig.sp
  scripting/get5/teamlogic.sp
  scripting/get5/util.sp
Labels: bug

#914 Add option to postpone stopping the demo recording
  documentation/docs/configuration.md
  documentation/docs/gotv.md
  scripting/get5.sp
  scripting/get5/recording.sp
  scripting/get5/surrender.sp
Labels: bug, enhancement

#908 Don't trigger auto-forfeit during warmup/veto + add option to disable forfeit
  documentation/docs/commands.md
  documentation/docs/configuration.md
  documentation/docs/translations.md
  scripting/get5.sp
  scripting/get5/surrender.sp
  scripting/include/get5.inc
Labels: enhancement

#912 Clean up tie/forfeit timer messages + don't end GOTV on readyup-timeout
  documentation/docs/translations.md
  scripting/get5.sp
  translations/chi/get5.phrases.txt
  translations/da/get5.phrases.txt
  translations/de/get5.phrases.txt
  translations/es/get5.phrases.txt
  translations/fr/get5.phrases.txt
  translations/get5.phrases.txt
  translations/hu/get5.phrases.txt
  translations/pl/get5.phrases.txt
  translations/pt/get5.phrases.txt
  translations/ru/get5.phrases.txt
Labels: enhancement, translation, Optimization/Cleanup

#907 Add message to inform players how to exit the coach slot
  documentation/docs/translations.md
  scripting/get5/teamlogic.sp
  translations/da/get5.phrases.txt
  translations/de/get5.phrases.txt
  translations/es/get5.phrases.txt
  translations/fr/get5.phrases.txt
  translations/get5.phrases.txt
  translations/hu/get5.phrases.txt
  translations/pl/get5.phrases.txt
  translations/pt/get5.phrases.txt
  translations/ru/get5.phrases.txt
Labels: enhancement, translation

#898 Update french translation
  translations/fr/get5.phrases.txt
Labels: translation

#922 Allow numbers in match config cvars section
  documentation/docs/match_schema.md
  scripting/get5/matchconfig.sp
Labels: bug

#921 Always handle GOTV memory leak problem, remove feature to toggle fix
  documentation/docs/configuration.md
  documentation/docs/gotv.md
  scripting/get5.sp
  scripting/get5/recording.sp
Labels: bug, enhancement

#923 Improve information on chat commands during warmup/preveto
  documentation/docs/commands.md
  documentation/docs/translations.md
  scripting/get5.sp
  scripting/get5/readysystem.sp
  scripting/get5/surrender.sp
  scripting/get5/teamlogic.sp
  translations/da/get5.phrases.txt
  translations/de/get5.phrases.txt
  translations/es/get5.phrases.txt
  translations/fr/get5.phrases.txt
  translations/get5.phrases.txt
  translations/hu/get5.phrases.txt
  translations/pl/get5.phrases.txt
  translations/pt/get5.phrases.txt
  translations/ru/get5.phrases.txt
Labels: bug, enhancement, translation
