Repository splewis/get5, pull requests merged in 2022-09, with the labels that each got.

#862 Get rid of g_WaitingForRoundBackup and introduce backup game state + clean up associated map-change logic and timers
  documentation/docs/commands.md
  scripting/get5.sp
  scripting/get5/backups.sp
  scripting/get5/debug.sp
  scripting/get5/kniferounds.sp
  scripting/get5/mapveto.sp
  scripting/get5/matchconfig.sp
  scripting/get5/readysystem.sp
  scripting/get5/stats.sp
  scripting/get5/util.sp
  scripting/include/get5.inc
Labels: breaking-changes

#863 Fix empty cvar problems with backups
  scripting/get5/matchconfig.sp
Labels: bug

#865 Auto-generated team names should be saved to stats KeyValue
  scripting/get5/matchconfig.sp
Labels: bug

#861 Add coaches to ready system via optional parameter
  documentation/docs/match_schema.md
  scripting/get5.sp
  scripting/get5/matchconfig.sp
  scripting/get5/readysystem.sp
  scripting/get5/tests.sp
  scripting/get5/version.sp
Labels: enhancement

#869 0.10.1
  documentation/docs/getting_started.md
  scripting/get5.sp
  scripting/get5/backups.sp
  scripting/get5/kniferounds.sp
  scripting/get5/matchconfig.sp
  scripting/get5/teamlogic.sp
  scripting/get5/version.sp
Labels: bug

#844 Add Support For Demo Uploads via HTTP & Demo Folder W/ Date Stamps
  documentation/docs/configuration.md
  documentation/docs/gotv.md
  documentation/docs/installation.md
  scripting/get5.sp
  scripting/get5/backups.sp
  scripting/get5/debug.sp
  scripting/get5/recording.sp
  scripting/get5/util.sp
Labels: enhancement

#868 Implemented bearer token parameter to get5_loadmatch_url
  .gitignore
  documentation/docs/commands.md
  scripting/get5.sp
  scripting/get5/matchconfig.sp
  scripting/get5/natives.sp
  scripting/include/get5.inc
Labels: enhancement

#876 0.10.2
  documentation/docs/commands.md
  documentation/docs/match_schema.md
  scripting/get5.sp
  scripting/get5/debug.sp
  scripting/get5/matchconfig.sp
  scripting/get5/natives.sp
  scripting/get5/stats.sp
  scripting/get5/teamlogic.sp
  scripting/get5/version.sp
Labels: bug, Optimization/Cleanup

#878 Fix Portuguese translation
  translations/pt/get5.phrases.txt
Labels: translation

#880 Fix problems with game going directly to live, skipping countdown
  scripting/get5.sp
  scripting/get5/goinglive.sp
  scripting/get5/kniferounds.sp
  scripting/get5/version.sp
  scripting/include/get5.inc
Labels: bug

#882 Allow disabling !forceready via get5_allow_force_ready.
  documentation/docs/commands.md
  documentation/docs/configuration.md
  documentation/docs/installation.md
  documentation/docs/translations.md
  scripting/get5.sp
  scripting/get5/readysystem.sp
  translations/chi/get5.phrases.txt
  translations/da/get5.phrases.txt
  translations/es/get5.phrases.txt
  translations/fr/get5.phrases.txt
  translations/get5.phrases.txt
  translations/hu/get5.phrases.txt
  translations/pt/get5.phrases.txt
  translations/ru/get5.phrases.txt
Labels: bug, enhancement, translation

#881 Use get5_server_id to prevent backup file collisions
  documentation/docs/backup.md
  documentation/docs/configuration.md
  scripting/get5/backups.sp
  scripting/get5/matchconfig.sp
Labels: enhancement, breaking-changes

#885 Allow sending events to remote URL
  documentation/docs/configuration.md
  documentation/docs/developers.md
  documentation/docs/event_schema.yml
  documentation/docs/events_and_forwards.md
  documentation/docs/gotv.md
  documentation/docs/installation.md
  scripting/get5.sp
  scripting/get5/events.sp
  scripting/get5/http.sp
  scripting/get5/recording.sp
Labels: enhancement

#887 Prevent multiple calls to !stop or the use of it during backup pause
  scripting/get5.sp
Labels: bug

#889 Use SteamWorks_SetHTTPRequestContextValue to pass demo file name
  scripting/get5.sp
  scripting/get5/debug.sp
  scripting/get5/recording.sp
Labels: bug, Optimization/Cleanup
