Repository splewis/get5, pull requests merged in 2022-07, with the labels that each got.

#785 Fix damage hook for bots
  scripting/get5.sp
Labels: bug

#787 Fix suicide logic (again) + self in grenade victim
  documentation/docs/event_schema.yml
  scripting/get5/stats.sp
  scripting/include/get5.inc
Labels: bug

#784 Clean up pause time counter logic
  documentation/docs/event_schema.yml
  scripting/get5.sp
  scripting/get5/backups.sp
  scripting/get5/debug.sp
  scripting/get5/goinglive.sp
  scripting/get5/mapveto.sp
  scripting/get5/matchconfig.sp
  scripting/get5/pausing.sp
  scripting/get5/util.sp
  scripting/include/get5.inc
  translations/chi/get5.phrases.txt
  translations/da/get5.phrases.txt
  translations/de/get5.phrases.txt
  translations/es/get5.phrases.txt
  translations/fr/get5.phrases.txt
  translations/get5.phrases.txt
  translations/pl/get5.phrases.txt
  translations/pt/get5.phrases.txt
  translations/ru/get5.phrases.txt
Labels: enhancement

#795 Consider "scrim" and "manual" matchID to be the same as no match ID for MySQL
  documentation/docs/commands.md
  documentation/docs/match_schema.md
  documentation/docs/stats_system.md
  scripting/get5/natives.sp
  scripting/get5_mysqlstats.sp
Labels: bug

#798 Simplify suicide logic
  scripting/get5/stats.sp
Labels: bug

#786 Add function to check for latest version of get5
  documentation/docs/commands.md
  documentation/docs/configuration.md
  documentation/docs/installation.md
  scripting/get5.sp
  scripting/get5/goinglive.sp
  scripting/get5/version.sp
  translations/get5.phrases.txt
Labels: enhancement

#802 Fix coach game prop when reconnect or calling !stop from match.
  scripting/get5/teamlogic.sp
Labels: bug

#805 Add hungarian translation
  translations/hu/get5.phrases.txt
Labels: translation
