Repository splewis/get5, pull requests merged in 2022-08, with the labels that each got.

#810 Add in checks for SVG logos
  scripting/get5/matchconfig.sp
Labels: bug

#809 Only print MoveToCoachInfoMessage if the user is a new coach
  scripting/get5/teamlogic.sp
Labels: bug

#806 Reorder parameters of get5_creatematch to match get5_scrim
  scripting/get5/matchconfig.sp
Labels: breaking-changes

#814 Init stats to zero
  documentation/docs/commands.md
  scripting/get5.sp
  scripting/get5/stats.sp
  scripting/get5/util.sp
  scripting/get5_apistats.sp
  scripting/include/get5.inc
Labels: enhancement

#815 Simplify CheckClientTeam and Update Coach Placement
  scripting/get5/teamlogic.sp
Labels: bug, enhancement

#793 Allow for backup prefix
  documentation/docs/backup.md
  documentation/docs/commands.md
  documentation/docs/configuration.md
  documentation/docs/developer_api.md
  documentation/docs/pausing.md
  documentation/docs/stats_system.md
  scripting/get5.sp
  scripting/get5/backups.sp
  scripting/get5/matchconfig.sp
  scripting/get5/stats.sp
Labels: enhancement

#818 Only allow one first kill per round, not per team
  scripting/get5.sp
  scripting/get5/stats.sp
Labels: enhancement, breaking-changes

#816 Move Match Cvars above series init
  scripting/get5/matchconfig.sp
Labels: bug

#824 Document map_sides
  documentation/docs/match_schema.md
  scripting/get5/readysystem.sp
  scripting/get5/util.sp
Labels: documentation

#833 Add configuration parameter for phase announcements + powered by get5 hardcode
  documentation/docs/configuration.md
  documentation/docs/translations.md
  scripting/get5.sp
  scripting/get5/goinglive.sp
  scripting/get5/kniferounds.sp
  scripting/get5/util.sp
  translations/chi/get5.phrases.txt
  translations/da/get5.phrases.txt
  translations/es/get5.phrases.txt
  translations/fr/get5.phrases.txt
  translations/get5.phrases.txt
  translations/hu/get5.phrases.txt
  translations/pt/get5.phrases.txt
Labels: enhancement

#835 Set non-empty team names if no player names was used
  scripting/get5/matchconfig.sp
Labels: bug

#836 Reset game state on backup load failure
  scripting/get5/backups.sp
Labels: bug

#841 Adjust GOTV and cvar restore logic
  cfg/get5/live.cfg
  cfg/get5/warmup.cfg
  documentation/docs/configuration.md
  documentation/docs/gotv.md
  documentation/docs/stats_system.md
  documentation/mkdocs.yml
  scripting/get5.sp
  scripting/get5/mapveto.sp
  scripting/get5/recording.sp
  scripting/get5/util.sp
Labels: bug

#843 Functions used in get5.inc should be included in that file
  scripting/get5/util.sp
  scripting/include/get5.inc
Labels: bug

#849 Ensure that g_MatchID is reset
  scripting/get5.sp
  scripting/get5/matchconfig.sp
Labels: bug

#852 Allow for setting the knife config file location
  documentation/docs/configuration.md
  scripting/get5.sp
Labels: enhancement

#851 Allow for customizing team color names
  documentation/docs/configuration.md
  scripting/get5.sp
  scripting/get5/matchconfig.sp
Labels: enhancement

#855 Udpate Command_Test to ensure it does not fail.
  scripting/get5.sp
  scripting/get5/matchconfig.sp
  scripting/get5/tests.sp
Labels: bug

#854 Reset votes to restore to start of round when a new backup is written
  documentation/docs/translations.md
  scripting/get5.sp
  translations/chi/get5.phrases.txt
  translations/da/get5.phrases.txt
  translations/de/get5.phrases.txt
  translations/es/get5.phrases.txt
  translations/fr/get5.phrases.txt
  translations/get5.phrases.txt
  translations/hu/get5.phrases.txt
  translations/pl/get5.phrases.txt
  translations/pt/get5.phrases.txt
  translations/ru/get5.phrases.txt
Labels: bug

#856 Remove deprecate bo2_series and maps_to_win match config params
  scripting/get5.sp
  scripting/get5/matchconfig.sp
  scripting/get5/tests.sp
Labels: breaking-changes

#847 Refactor coach and team-assignment logic
  cfg/get5/warmup.cfg
  documentation/docs/backup.md
  documentation/docs/coaching.md
  documentation/docs/commands.md
  documentation/docs/configuration.md
  documentation/docs/getting_started.md
  documentation/docs/gotv.md
  documentation/docs/match_schema.md
  documentation/docs/translations.md
  documentation/mkdocs.yml
  scripting/get5.sp
  scripting/get5/backups.sp
  scripting/get5/debug.sp
  scripting/get5/goinglive.sp
  scripting/get5/kniferounds.sp
  scripting/get5/mapveto.sp
  scripting/get5/matchconfig.sp
  scripting/get5/stats.sp
  scripting/get5/teamlogic.sp
  scripting/get5/tests.sp
  scripting/get5/util.sp
  translations/da/get5.phrases.txt
  translations/get5.phrases.txt
Labels: bug, enhancement, documentation

#857 Various adjustments to 0.10
  documentation/docs/configuration.md
  documentation/docs/translations.md
  scripting/get5.sp
  scripting/get5/backups.sp
  scripting/get5/debug.sp
  scripting/get5/maps.sp
  scripting/get5/mapveto.sp
  scripting/get5/matchconfig.sp
  scripting/get5/recording.sp
  scripting/get5/stats.sp
  scripting/get5/util.sp
  translations/da/get5.phrases.txt
  translations/get5.phrases.txt
Labels: bug, breaking-changes
