Repository splewis/get5, pull requests merged in 2023-02, with the labels that each got.

#910 Don't consume pauses until they start + GSI support + Pause begin forward/event
  documentation/docs/backup.md
  documentation/docs/configuration.md
  documentation/docs/event_schema.yml
  documentation/docs/events_and_forwards.md
  documentation/docs/pausing.md
  documentation/docs/translations.md
  scripting/get5.sp
  scripting/get5/backups.sp
  scripting/get5/mapveto.sp
  scripting/get5/matchconfig.sp
  scripting/get5/pausing.sp
  scripting/include/get5.inc
  translations/chi/get5.phrases.txt
  translations/da/get5.phrases.txt
  translations/de/get5.phrases.txt
  translations/es/get5.phrases.txt
  translations/fr/get5.phrases.txt
  translations/get5.phrases.txt
  translations/hu/get5.phrases.txt
  translations/pl/get5.phrases.txt
  translations/pt/get5.phrases.txt
  translations/ru/get5.phrases.txt
Labels: enhancement, request for feedback, breaking-changes

#968 Fix translations
  translations/fr/get5.phrases.txt
  translations/hu/get5.phrases.txt
  translations/pl/get5.phrases.txt
Labels: translation

#969 Create chat-based map selection system
  configs/get5/tests/maplist_duplicate_map.json
  documentation/docs/commands.md
  documentation/docs/configuration.md
  documentation/docs/pausing.md
  documentation/docs/surrender-forfeit.md
  documentation/docs/translations.md
  documentation/docs/veto.md
  scripting/get5.sp
  scripting/get5/chatcommands.sp
  scripting/get5/kniferounds.sp
  scripting/get5/mapveto.sp
  scripting/get5/matchconfig.sp
  scripting/get5/readysystem.sp
  scripting/get5/surrender.sp
  scripting/get5/tests.sp
  scripting/get5/util.sp
  scripting/include/get5.inc
  translations/chi/get5.phrases.txt
  translations/da/get5.phrases.txt
  translations/de/get5.phrases.txt
  translations/es/get5.phrases.txt
  translations/fr/get5.phrases.txt
  translations/get5.phrases.txt
  translations/hu/get5.phrases.txt
  translations/pt/get5.phrases.txt
  translations/ru/get5.phrases.txt
Labels: enhancement, translation

#971 Add Turkish translation
  documentation/docs/translations.md
  translations/tr/get5.phrases.txt
Labels: translation

#970 Added Greek translations.
  translations/el/get5.phrases.txt
Labels: translation

#972 Add `get5_add_ready_time`
  documentation/docs/commands.md
  scripting/get5.sp
  scripting/get5/readysystem.sp
Labels: enhancement

#974 Allow workshop maps in maplist
  documentation/docs/match_schema.md
  documentation/docs/stats_system.md
  scripting/get5.sp
  scripting/get5/maps.sp
  scripting/get5/mapveto.sp
  scripting/get5/matchconfig.sp
  scripting/get5/tests.sp
  scripting/get5/util.sp
Labels: enhancement

#978 Add support for Wingman + clean up default configs + fix mapchange with workshop map
  cfg/get5/knife.cfg
  cfg/get5/live.cfg
  cfg/get5/live_wingman.cfg
  cfg/get5/warmup.cfg
  documentation/docs/configuration.md
  documentation/docs/match_schema.md
  documentation/docs/wingman.md
  documentation/mkdocs.yml
  scripting/get5.sp
  scripting/get5/backups.sp
  scripting/get5/debug.sp
  scripting/get5/goinglive.sp
  scripting/get5/maps.sp
  scripting/get5/mapveto.sp
  scripting/get5/matchconfig.sp
  scripting/get5/tests.sp
  scripting/get5/util.sp
Labels: bug, enhancement

#979 Fix workshop map names in backups
  configs/get5/tests/default_valid.cfg
  configs/get5/tests/default_valid.json
  scripting/get5/backups.sp
  scripting/get5/matchconfig.sp
  scripting/get5/tests.sp
  scripting/get5/util.sp
Labels: bug

#982 Automatically adjust minimum surrender votes
  documentation/docs/configuration.md
  scripting/get5/surrender.sp
  scripting/get5/util.sp
Labels: bug

#985 Add kick get5_kick_on_force_end
  CHANGELOG.md
  documentation/docs/commands.md
  documentation/docs/configuration.md
  scripting/get5.sp
Labels: enhancement

#983 Add Swedish
  translations/el/get5.phrases.txt
  translations/se/get5.phrases.txt
Labels: translation

#981 Adjust chinese
  translations/chi/get5.phrases.txt
Labels: translation

#987 Compile with SM 1.11
  .github/workflows/build.yml
  .github/workflows/development.yml
  Dockerfile
  dockerrunscript.sh
  documentation/docs/developers.md
  scripting/get5.sp
  scripting/get5/events.sp
  scripting/get5/get5menu.sp
  scripting/get5/goinglive.sp
  scripting/get5/kniferounds.sp
  scripting/get5/matchconfig.sp
  scripting/get5/natives.sp
  scripting/get5/pausing.sp
  scripting/get5/readysystem.sp
  scripting/get5/stats.sp
  scripting/get5/teamlogic.sp
  scripting/get5/tests.sp
  scripting/get5/util.sp
  scripting/get5/version.sp
  scripting/get5_apistats.sp
  scripting/get5_mysqlstats.sp
  smbuild
Labels: enhancement
